Added modifies clause generation for Boogie files.
smackers/smack pull request #267
Opened 2017-09-19 05:54 UTC by liammachado

Modifies clause generation is now directly integrated into the SMACK tool, rather than being done by Corral/Boogie.

2017-09-19 05:55 UTC, liammachado commented
Sorry for creating a new pull request, I mistakenly deleted my fork instead of updating it with the new develop branch changes.

2017-10-06 18:59 UTC, zvonimir requested changes
More to come.

2017-10-06 18:59 UTC, zvonimir commented on CMakeLists.txt
> +  include/smack/GenModifies.h
I think that naming this file `ModAnalysis` would be better. So update its name.

2017-10-06 18:59 UTC, zvonimir commented on include/smack/GenModifies.h
> +#ifndef MODS_H
Change the file name to `ModAnalysis.h`.
Also, this should be `#ifndef MODANALYSIS_H` to make it consistent with other files.

2017-10-06 18:59 UTC, zvonimir commented on include/smack/GenModifies.h
> +#define MODS_H
See above comment. Change this to `MODANALYSIS_H`

2017-10-06 18:59 UTC, zvonimir commented on share/smack/top.py
> +    #command += ["/nologo", "/noinfer", "/doModSetAnalysis"]
Don't comment this whole line out. Just remove `/doModSetAnalysis`

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2017-10-06 18:59 UTC, zvonimir commented on lib/smack/GenModifies.cpp
> +
Remove this empty line, it is not needed here.

2026-07-05 05:23 UTC, closed without merging