Copy
smackers/smack pull request #666
Opened 2020-12-14 07:17 UTC by shaobo-he

2020-12-17 03:06 UTC, zvonimir commented
What does this do? I don't quite get it.

2020-12-17 03:55 UTC, shaobo-he commented
> What does this do? I don't quite get it.

This is to provide more precise error traces for memory-safety violations. If you run the regressions in this PR using the develop branch, you should notice that the error trace is weird.

2020-12-17 04:08 UTC, zvonimir commented
What happened with CI here?

2020-12-17 04:11 UTC, zvonimir requested changes

2020-12-17 04:11 UTC, zvonimir commented on test/c/memory-safety/test_sourceloc.c
> +int main() {
This should be `int main(void)`

2020-12-17 04:11 UTC, zvonimir commented on test/c/memory-safety/test_sourceloc_fail.c
> +int main() {
This should be `int main(void)`

2020-12-17 05:43 UTC, shaobo-he commented
> What happened with CI here?

It's related to this issue: https://github.com/smackers/smack/issues/668

2020-12-19 17:47 UTC, zvonimir commented
Hey @shaobo-he . I can't merge this until CI is fixed. What is happening there?

2020-12-19 17:47 UTC, zvonimir commented
How is it related to the issue you pointed out? I don't understand how come that regression works now?

2020-12-19 17:48 UTC, zvonimir commented
Ah, I see. You added a regression! Ok, issue #668 might be an easy fix. Can you take care of that one first then? Or how should we go about this?

2020-12-19 21:24 UTC, shaobo-he commented
> Ah, I see. You added a regression! Ok, issue #668 might be an easy fix. Can you take care of that one first then? Or how should we go about this?

Yes, I think I'll fix it first.

2020-12-20 07:05 UTC, shaobo-he commented
@zvonimir please see https://github.com/smackers/smack/pull/670.

2020-12-21 06:41 UTC, zvonimir approved these changes
Looks good to me.

2020-12-21 07:15 UTC, merged