Fixes to run SMACK on modern macOS
smackers/smack pull request #789
Opened 2022-07-01 20:26 UTC by keram88

This PR addresses the following: 
* Improves path manipulation in `regtest.py` to be more compatible with macOS (based on work by @shaobo-he)
* Extends the expected name for `bc` files generated by `cargo` to support an optional 16 digit hash

Co-authored-by: @shaobo-he

2022-07-01 20:50 UTC, zvonimir requested changes

2022-07-01 20:50 UTC, zvonimir commented on share/smack/frontend.py
> +    target_pat = target_name + r'(-[a-f0-9]{16})?\.bc'
should this be `target_path` maybe?

2022-07-01 20:50 UTC, zvonimir commented on share/smack/frontend.py
> +    target_pat = target_name + r'(-[a-f0-9]{16})?\.bc'
Oh, I see. It should be `target_pattern`.

2023-03-22 22:02 UTC, zvonimir approved these changes
LGTM

2023-03-22 22:08 UTC, shaobo-he approved these changes

2023-03-23 18:56 UTC, rakamaric commented
@keram88 so something is failing in regtest.py. It seems that it is maybe not opening config file properly or something like that. Could you please debug this? See the failing CI.

2023-03-24 22:10 UTC, zvonimir approved these changes
LGTM

2023-03-24 22:10 UTC, merged